apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaschenpost-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaschenpost
  template:
    metadata:
      labels:
        app: flaschenpost
    spec:
      containers:
        - name: flaschenpost-container
          image: strm/helloworld-http:latest
          ports:
            - containerPort: 80
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
            failureThreshold: 2
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flaschenpost-cron
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: flaschenpost-job
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Hello SRE"
          restartPolicy: OnFailure

