apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: azure-infra-provision
  title: Azure Infra Provisioning Template
  description: Template to provision Azure Resource Group, Storage Account and Container using Terraform.
  tags:
    - azure
    - terraform
spec:
  owner: your-team@example.com
  type: service

  parameters:
    - title: Azure Resource Group
      required:
        - resource_group_name
      properties:
        resource_group_name:
          type: string
          title: Resource Group Name
          description: Name of the Azure Resource Group to be created.
        resource_group_tag:
          type: object
          title: Resource Group Tag
          description: Key-value tag for the resource group.
          default:
            department: SRE

    - title: Azure Storage Account
      required:
        - storage_account_name
      properties:
        storage_account_name:
          type: string
          title: Storage Account Name
          description: Name of the Azure Storage Account.
        storage_account_resource_group:
          type: string
          title: Storage Account Resource Group
          description: Resource group to associate with Storage Account.
          default: sre-challenge-flaschenpost
        sku:
          type: string
          title: Storage Account SKU
          description: SKU of the storage account.
          enum:
            - Standard_LRS
            - Premium_LRS
            - Standard_GRS
          default: Standard_LRS
        access_tier:
          type: string
          title: Access Tier
          description: Access tier for storage account.
          enum:
            - Hot
            - Cool
          default: Hot
        storage_account_tag:
          type: object
          title: Storage Account Tag
          description: Key-value tag for the storage account.
          default:
            department: SRE

    - title: Storage Account Container
      required:
        - container_name
      properties:
        container_name:
          type: string
          title: Container Name
          description: Name of the storage container within the storage account.
          default: sre
        container_type:
          type: string
          title: Container Type
          description: Type of container.
          enum:
            - private
            - blob
          default: private

  steps:
    - id: generate
      name: Generate Terraform Files
      action: scaffolder:template
      input:
        values:
          resource_group_name: ${{ parameters.resource_group_name }}
          resource_group_tag: ${{ parameters.resource_group_tag }}
          storage_account_name: ${{ parameters.storage_account_name }}
          storage_account_resource_group: ${{ parameters.storage_account_resource_group }}
          sku: ${{ parameters.sku }}
          access_tier: ${{ parameters.access_tier }}
          storage_account_tag: ${{ parameters.storage_account_tag }}
          container_name: ${{ parameters.container_name }}
          container_type: ${{ parameters.container_type }}
        templateDir: ./terraform-template

