apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-job
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Hello SRE"
              securityContext:
                runAsUser: 1000               # Run as non-root user
                runAsNonRoot: true
                readOnlyRootFilesystem: true # Make filesystem read-only
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                    - ALL
          restartPolicy: OnFailure
