apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Release.Name }}-job
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Hello SRE"
          restartPolicy: OnFailure
